# This workflow will review a GloBI indexed dataset.
# For more information see: https://globalbioticinteractions.org

name: GloBI review by Elton

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: download review script
        run: curl --silent -L "https://raw.githubusercontent.com/globalbioticinteractions/globinizer/master/check-dataset.sh" > check-dataset.sh
      - name: download network compiler script
        run: |
          curl --silent -L "https://raw.githubusercontent.com/globalbioticinteractions/globinizer/master/compile-network.sh" > compile-network.sh
          chmod +x compile-network.sh
      - name: review dataset
        run: bash check-dataset.sh "${GITHUB_REPOSITORY}"
      - name: Share review report
        uses: actions/upload-artifact@v4
        with:
          name: review-report
          path: |
            README.txt
            datasets/
            index.*
            indexed-*
            review*
